<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@hasSection('page-title')@yield('page-title') | @endif{{ setting('app_name') }}</title>
<link href="{{ elixir('assets/css/admin.css') }}" rel="stylesheet">
</head>
<body>
@yield('content')
<div class="footer footer-boxed text-muted text-center">This document is generated by using {{ setting('app-name') }} hence no signature is required.</div>
</body>
</html>
